# Inside this file is the configuration options
# for the data sources that SMW supports
mysql:
  enabled: false
  host: 127.0.0.1
  port: 3306
  username: slimeworldmanager
  password: ''
  database: slimeworldmanager
mongodb:
  enabled: false
  host: 127.0.0.1
  port: 27017
  username: slimeworldmanager
  password: ''
  database: slimeworldmanager
  collection: worlds